//! See docs/superpowers/specs/2026-09-01-castr-core-design.md
pub mod header;
pub use header::*;
pub mod packetize;
pub use packetize::*;
pub mod reassemble;
pub use reassemble::*;
pub mod control;
pub use control::*;
